### ISSUE TITLE
No successful drops in 3.1.1?

### ISSUE THREAD

**Issue by tias79** [norpan/elm-html5-drag-drop#13] opened 2018-11-25 09:30 UTC
I was using 3.0.2, but had some trouble with the virtual DOM breaking, so I upgraded to 3.1.1. However, with 3.1.1 I get no successful drops at all. I tried downgrading to 3.1.0, where I get successful drops again, but also some issues with the virtual DOM.

I'm using droppables inside droppables, why I was curious about this comment which seems to end prematurely:
https://github.com/norpan/elm-html5-drag-drop/blob/master/src/Html5/DragDrop.elm#L249

**Comment by norpan** [comment] 2018-11-25 09:37
Thanks for the issue! I'm currently fixing some other stuff (#12) that may have influence on this issue too. Do you have a simple example that doesn't work, and also, what browser(s) have you tried?

**Comment by tias79** [comment] 2018-11-25 14:03
I've only tried Chrome.

I don't have a simple example, only a more complex one: https://github.com/tias79/stickystories
It's an app created with create-elm-app, and basically a UI mockup with no backend, so you can just fire it up and start poking around. However, it's currently running 3.0.2.

Later tonight I can try and isolate the problem to a simpler example, if possible.

**Comment by norpan** [comment] 2018-11-25 14:12
Thanks! I tested it out, and I think the problem indeed is related to #12, you get a dragenter, but then you get a dragleave event. I think this is because the dragenter event is being propagated, which it shouldn't be. I'll make a new version where it isn't and let you know.

**Comment by norpan** [comment] 2018-11-26 08:35
Hi, I have made a new version with stopped propagation of events. Could you try with versions 3.0.0, 3.0.1, 3.1.0, 3.1.1 and 3..1.2 and see if your problem is fixed in any of those. That will give me good information about what the source of the problem is.

**Comment by panthus** [comment] 2018-11-27 13:54
I found the issue with Google Chrome. Apparently it uses a  `DOMHighResTimeStamp` for the timeStamp attribute which is a float instead of an int, see https://developers.google.com/web/updates/2016/01/high-res-timestamps.

**Comment by norpan** [comment] 2018-11-27 14:29
Great! I'll make a new version that parses as float and rounds to int.

**Closed as completed** 2018-11-27 14:33 UTC

**Comment by panthus** [comment] 2018-11-27 14:38
I verified that Google Chrome works again in 3.1.3, thanks!
